#!/bin/bash
loadkeys uk
timedatectl set-ntp 1
# make sure that the disk has been wiped
sgdisk --zap-all /dev/sda
# create a single, bootable disk partition
sfdisk /dev/sda << _EOF_
,,,*;
_EOF_
# make ext4 file system
mkfs.ext4 /dev/sda1
# mount the partition
mount /dev/sda1 /mnt
# install arch linux
pacstrap -i /mnt base base-devel
genfstab -U -p /mnt >> /mnt/etc/fstaISOb
arch-chroot /mnt /bin/bash < ./arch_chroot

